apiVersion: apps/v1
kind: Deployment
metadata:
  name: samlidp
  namespace: saml-tools
  labels:
    app: samlidp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samlidp
  template:
    metadata:
      labels:
        app: samlidp
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: key-converter
        image: alpine:latest
        securityContext:
          runAsUser: 0  # Run as root for apt operations
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Checking key format..."
          mkdir -p /tmp/certs
          cat /certs/tls.crt > /tmp/certs/cert.pem
          
          # Extract the key and convert it to PKCS1 format if needed
          echo "Converting key to PKCS1 format..."
          apk add --no-cache openssl
          cat /certs/tls.key > /tmp/certs/key_orig.pem
          openssl rsa -in /tmp/certs/key_orig.pem -out /tmp/certs/key.pem
          rm /tmp/certs/key_orig.pem
          
          chmod 600 /tmp/certs/key.pem
          echo "Certificate and key prepared in /tmp/certs/"
        volumeMounts:
        - name: cert-volume
          mountPath: /certs/
        - name: converted-certs
          mountPath: /tmp/certs/
      containers:
      - name: samlidp
        image: registry.digitalocean.com/samltools/samlidp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        env:
        - name: CONFIG_FILE
          value: "/app/configs/samlidp.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs/
        - name: converted-certs
          mountPath: /app/certs/idp/
        readinessProbe:
          httpGet:
            path: /
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      volumes:
      - name: config-volume
        configMap:
          name: samlidp-config
      - name: cert-volume
        secret:
          secretName: idp-tls-cert
      - name: converted-certs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: samlidp
  namespace: saml-tools
spec:
  selector:
    app: samlidp
  ports:
  - port: 8085
    targetPort: 8085
    name: http
  type: ClusterIP