apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@saml-tester.com
    privateKeySecretRef:
      name: letsencrypt-prod-dns01
    solvers:
    - dns01:
        cloudflare:
          email: admin@saml-tester.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
          - "saml-tester.com"