# SAML Proxy Configuration with Multiple IdPs

# Server configuration
listen_addr: ":8082"
base_url: "http://samlproxy:8082"
cert_file: "./certs/proxy/cert.pem"
key_file: "./certs/proxy/key.pem"
session_secret: "a-strong-random-secret-key-here"

# Proxy configuration
proxy_entity_id: "http://samlproxy:8082/metadata"

# Debug mode
debug: true

# Service Provider configurations
service_providers:
  - name: "SAML Client"
    entity_id: "urn:samlclient:sp"
    acs_url: "http://samlclient:8080/saml/acs"
    metadata_xml_url: "http://samlclient:8080/saml/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

  - name: "Salesforce"
    entity_id: "https://beyondidentity-dev-ed.develop.my.salesforce.com"
    acs_url: "https://beyondidentity-dev-ed.develop.my.salesforce.com"
    metadata_xml_url: "https://beyondidentity-dev-ed.develop.my.salesforce.com/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

  - name: "Cloudflare"
    entity_id: "urn:samlclient:sp"
    acs_url: "http://samlclient:8080/saml/acs"
    metadata_xml_url: "http://samlclient:8080/saml/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

# Identity Provider configurations
identity_providers:
  - id: "test-idp"
    name: "Test IDP"
    description: "A custom test identity provider"
    logo_url: "https://dummyimage.com/100x60/f5f2f5/0a1066.png&text=Test"
    metadata_url: "http://samlidp:8085/metadata"
    entity_id: "http://samlidp:8085/metadata"
    sso_url: "http://samlidp:8085/sso"
    default_idp: false

  - id: "dev-okta"
    name: "Dev Okta"
    description: "Dev Okta Tenant"
    logo_url: "https://dummyimage.com/100x60/f5f2f5/0a1066.png&text=Okta"
    metadata_url: "https://dev-115454.okta.com/app/exkr2t2cpcWXWtnqN4x7/sso/saml/metadata"
    entity_id: "http://www.okta.com/exkr2t2cpcWXWtnqN4x7"
    sso_url: "https://dev-115454.okta.com/app/dev-115454_samlproxy_1/exkr2t2cpcWXWtnqN4x7/sso/saml"

  - id: "bi-nmelo-okta"
    name: "BI nmelo-okta"
    description: "Nelson's BI Tenant"
    logo_url: "https://dummyimage.com/100x60/f5f2f5/0a1066.png&text=nmelo-okta"
    metadata_url: "https://auth.byndid.com/saml/v0/dc90eac1-a91e-46ff-b25d-cad53d93caad/sso/metadata.xml"
    entity_id: "https://auth.byndid.com/saml/v0/dc90eac1-a91e-46ff-b25d-cad53d93caad/sso/metadata.xml"
    sso_url: "https://auth.byndid.com/saml/v0/dc90eac1-a91e-46ff-b25d-cad53d93caad/sso"
