# SAML Identity Provider Configuration

# Server configuration
listen_addr: ":8085"
base_url: "http://localhost:8085"
cert_file: "./certs/idp/cert.pem"
key_file: "./certs/idp/key.pem"
session_secret: "idp-strong-secret-key-here"

# IdP configuration
entity_id: "http://localhost:8085/metadata"
metadata_path: "/metadata"
sso_service_path: "/sso"

# User accounts
users:
  - username: "admin"
    password: "admin123"
    attributes:
      email: "admin@example.com"
      firstName: "Admin"
      lastName: "User"
      roles: ["admin", "user"]
      userId: "1001"
  
  - username: "user"
    password: "user123"
    attributes:
      email: "user@example.com"
      firstName: "Regular"
      lastName: "User"
      roles: ["user"]
      userId: "1002"