# SAML Proxy Configuration with Multiple IdPs

# Server configuration
listen_addr: ":8082"
base_url: "http://samlproxy:8082"
cert_file: "./certs/proxy/cert.pem"
key_file: "./certs/proxy/key.pem"
session_secret: "a-strong-random-secret-key-here"

# Proxy configuration
proxy_entity_id: "http://samlproxy:8082/metadata"

# Debug mode
debug: true

# Service Provider configurations
service_providers:
  - name: "SAML Client"
    entity_id: "urn:samlclient:sp"
    acs_url: "http://samlclient:8080/saml/acs"
    metadata_xml_url: "http://samlclient:8080/saml/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

  - name: "Salesforce"
    entity_id: "https://beyondidentity-dev-ed.develop.my.salesforce.com"
    acs_url: "https://beyondidentity-dev-ed.develop.my.salesforce.com"
    metadata_xml_url: "https://beyondidentity-dev-ed.develop.my.salesforce.com/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

# Identity Provider configurations
identity_providers:
  - id: "bi-v0-demo"
    name: "Secure Workforce"
    description: "Secure Workforce demo tenant"
    logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjOPILVZchS8DNurm0v8zXqRS783BNh_Mqyw&s"
    metadata_url: "https://auth.byndid.com/saml/v0/38e2efe8-6891-48cd-a36d-560aa4999918/sso/metadata.xml"
    entity_id: "https://auth.byndid.com/saml/v0/38e2efe8-6891-48cd-a36d-560aa4999918/sso/metadata.xml"
    sso_url: "https://auth.byndid.com/saml/v0/38e2efe8-6891-48cd-a36d-560aa4999918/sso"

  - id: "bi-v1-demo"
    name: "Secure Access"
    description: "Secure Access demo tenant"
    logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjOPILVZchS8DNurm0v8zXqRS783BNh_Mqyw&s"
    metadata_url: "https://auth-us.beyondidentity.com/v1/tenants/00016b5be85b2cd5/realms/b6bf37e4d930855a/applications/0692eb8e-b547-4c46-b325-026c224b2c25/saml/idp/metadata"
    entity_id: "https://auth-us.beyondidentity.com/v1/tenants/00016b5be85b2cd5/realms/b6bf37e4d930855a/applications/0692eb8e-b547-4c46-b325-026c224b2c25/saml/idp/metadata"
    sso_url: "https://auth-us.beyondidentity.com/v1/tenants/00016b5be85b2cd5/realms/b6bf37e4d930855a/applications/0692eb8e-b547-4c46-b325-026c224b2c25/saml/sp/initiate"

  - id: "demo-okta"
    name: "Okta"
    description: "Okta Demo tenant"
    logo_url: "https://logos-world.net/wp-content/uploads/2021/04/Okta-Emblem.png"
    metadata_url: "https://dev-25589801.okta.com/app/exkosu991m6t4cNgP5d7/sso/saml/metadata"
    entity_id: "http://www.okta.com/exkosu991m6t4cNgP5d7"
    sso_url: "https://dev-25589801.okta.com/app/dev-25589801_idpselector_1/exkosu991m6t4cNgP5d7/sso/saml"

  - id: "demo-entra"
    name: "Entra ID"
    description: "Entra Demo tenant"
    logo_url: "https://cdn.worldvectorlogo.com/logos/azure-1.svg"
    metadata_url: "https://login.microsoftonline.com/7ac90e8a-2659-478d-b86b-28e67956e246/federationmetadata/2007-06/federationmetadata.xml?appid=74ba93fe-ef30-4634-95fe-546977c7b041"
    entity_id: "https://sts.windows.net/7ac90e8a-2659-478d-b86b-28e67956e246/"
    sso_url: "https://login.microsoftonline.com/7ac90e8a-2659-478d-b86b-28e67956e246/saml2"

  - id: "demo-onelogin"
    name: "OneLogin"
    description: "OneLogin Demo tenant"
    logo_url: "https://www.onelogin.com/press-center/wp-content/themes/oceanwp-child-theme-master/assets/Onelogin_Mark_black_RGB.png"
    metadata_url: "https://app.onelogin.com/saml/metadata/a7e7b19d-75a0-4876-bd7d-3d6cdbd1f3e4"
    entity_id: "https://app.onelogin.com/saml/metadata/a7e7b19d-75a0-4876-bd7d-3d6cdbd1f3e4"
    sso_url: "https://byndid-dev.onelogin.com/trust/saml2/http-post/sso/a7e7b19d-75a0-4876-bd7d-3d6cdbd1f3e4"

  - id: "demo-pingfederate"
    name: "PingFederate"
    description: "PingFederate Demo tenant"
    logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR3gpOzocJjYRVxeWVCDLeGv64nd7syG9JAQ&s"
    metadata_url: "https://byndid-ping.com:9031/idp/startSSO.ping/pf/federation_metadata.ping"
    entity_id: "https://byndid-ping.com:9031/idp/startSSO.ping"
    sso_url: "https://byndid-ping.com:9031/idp/SSO.saml2"

  - id: "demo-shibboleth"
    name: "Shibboleth"
    description: "Shibboleth Demo tenant"
    logo_url: "https://www.icontechnicalgroup.com//wp-content/uploads/2017/09/ShibbolethLogo.png"
    metadata_url: "https://byndid-shibboleth.com/idp/shibboleth"
    entity_id: "https://byndid-shibboleth.com/idp"
    sso_url: "https://byndid-shibboleth.com/idp/profile/SAML2/POST/SSO"
    authn_context_class_ref: "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified"

  - id: "demo-adfs"
    name: "ADFS"
    description: "ADFS Demo tenant"
    logo_url: "https://www.icontechnicalgroup.com//wp-content/uploads/2017/09/ShibbolethLogo.png"
    metadata_url: "https://ec2amaz-8c8qrmr.byndid-mail.com/FederationMetadata/2007-06/FederationMetadata.xml"
    entity_id: "https://EC2AMAZ-8C8QRMR.byndid-mail.com/adfs/services/trust"
    sso_url: "https://EC2AMAZ-8C8QRMR.byndid-mail.com/adfs/ls"
    authn_context_class_ref: "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified"

  - id: "test-idp"
    name: "Test IDP"
    description: "A custom identity provider for testing"
    logo_url: "https://www.pngkey.com/png/detail/46-463151_identity-access-and-management-engine-provides-individuals-privacy.png"
    metadata_url: "http://samlidp:8085/metadata"
    entity_id: "http://samlidp:8085/metadata"
    sso_url: "http://samlidp:8085/sso"
    default_idp: false
    authn_context_class_ref: "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified"
