# SAML Proxy Configuration with Multiple IdPs

# Server configuration
listen_addr: ":8082"
base_url: "http://samlproxy:8082"
cert_file: "./certs/proxy/cert.pem"
key_file: "./certs/proxy/key.pem"
session_secret: "a-strong-random-secret-key-here"

# Proxy configuration
proxy_entity_id: "http://samlproxy:8082/metadata"

# Debug mode
debug: true

# Health check interval in seconds for Identity Providers (e.g., 60 for 1 minute).
# If not specified, defaults to 60 seconds.
health_check_interval_seconds: 60

# Service Provider configurations
service_providers:
  - name: "SAML Client"
    entity_id: "urn:samlclient:sp"
    acs_url: "http://samlclient:8080/saml/acs"
    metadata_xml_url: "http://samlclient:8080/saml/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

  - name: "Salesforce"
    entity_id: "https://beyondidentity-dev-ed.develop.my.salesforce.com"
    acs_url: "https://beyondidentity-dev-ed.develop.my.salesforce.com"
    metadata_xml_url: "https://beyondidentity-dev-ed.develop.my.salesforce.com/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

  - name: "Cloudflare"
    entity_id: "urn:samlclient:sp"
    acs_url: "http://samlclient:8080/saml/acs"
    metadata_xml_url: "http://samlclient:8080/saml/metadata"
    attribute_map:
      "email": "email"
      "username": "username"
      "firstName": "firstName"
      "lastName": "lastName"
      "userId": "userId"
      "roles": "roles"
      "idpId": "idp_id"
      "idpName": "idp_name"

# Identity Provider configurations
identity_providers:
  - id: "bi-v0-demo"
    name: "Secure Workforce"
    description: "Secure Workforce demo tenant"
    logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjOPILVZchS8DNurm0v8zXqRS783BNh_Mqyw&s"
    metadata_url: "https://auth.byndid.com/saml/v0/38e2efe8-6891-48cd-a36d-560aa4999918/sso/metadata.xml"
    entity_id: "https://auth.byndid.com/saml/v0/38e2efe8-6891-48cd-a36d-560aa4999918/sso/metadata.xml"
    sso_url: "https://auth.byndid.com/saml/v0/38e2efe8-6891-48cd-a36d-560aa4999918/sso"
    # Optional: URL for health check. If not provided or empty, metadata_url will be used for the health check.
    # Replace with a specific health check endpoint for this IdP if available.
    health_check_url: "https://auth.byndid.com/healthz" # Example: using a hypothetical health endpoint

  - id: "bi-v1-demo"
    name: "Secure Access"
    description: "Secure Access demo tenant"
    logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjOPILVZchS8DNurm0v8zXqRS783BNh_Mqyw&s"
    metadata_url: "https://auth-us.beyondidentity.com/v1/tenants/00016b5be85b2cd5/realms/b6bf37e4d930855a/applications/0692eb8e-b547-4c46-b325-026c224b2c25/saml/idp/metadata"
    entity_id: "https://auth-us.beyondidentity.com/v1/tenants/00016b5be85b2cd5/realms/b6bf37e4d930855a/applications/0692eb8e-b547-4c46-b325-026c224b2c25/saml/idp/metadata"
    sso_url: "https://auth-us.beyondidentity.com/v1/tenants/00016b5be85b2cd5/realms/b6bf37e4d930855a/applications/0692eb8e-b547-4c46-b325-026c224b2c25/saml/sp/initiate"

  - id: "demo-okta"
    name: "Okta"
    description: "Okta Demo tenant"
    logo_url: "https://logos-world.net/wp-content/uploads/2021/04/Okta-Emblem.png"
    metadata_url: "https://dev-115454.okta.com/app/exkr2t2cpcWXWtnqN4x7/sso/saml/metadata"
    entity_id: "http://www.okta.com/exkr2t2cpcWXWtnqN4x7"
    sso_url: "https://dev-115454.okta.com/app/dev-115454_samlproxy_1/exkr2t2cpcWXWtnqN4x7/sso/saml"
    # Optional: health_check_url. If omitted or left empty, metadata_url is used by default for health checks.
    # For Okta, their metadata URL often serves as a good basic health indicator.
    # health_check_url: ""

  - id: "test-idp"
    name: "Test IDP"
    description: "A custom identity provider for testing"
    logo_url: "https://www.pngkey.com/png/detail/46-463151_identity-access-and-management-engine-provides-individuals-privacy.png"
    metadata_url: "http://samlidp:8085/metadata"
    entity_id: "http://samlidp:8085/metadata"
    sso_url: "http://samlidp:8085/sso"
    default_idp: false
